#! /usr/bin/env python3

from argparse import ArgumentParser, REMAINDER
import subprocess


argument_parser = ArgumentParser(description=__doc__)
argument_parser.add_argument('dmenu_args', nargs=REMAINDER,
                             help='Command line arguments'
                                  ' to pass through to dmenu')

net_active_window = subprocess.run(['xprop',
                                    '-root',
                                    '32x', '\\t$0',
                                    '_NET_ACTIVE_WINDOW'],
                                   check=True,
                                   stdin=subprocess.DEVNULL,
                                   stdout=subprocess.PIPE,
                                   stderr=subprocess.PIPE,
                                   universal_newlines=True) \
                              .stdout \
                              .rsplit('\t', maxsplit=1)[-1]

dmenu_args = argument_parser.parse_args().dmenu_args
title = subprocess.run(["dmenu"] + dmenu_args[1:],
                       check=True,
                       stdin=subprocess.DEVNULL,
                       stdout=subprocess.PIPE,
                       stderr=subprocess.PIPE,
                       universal_newlines=True).stdout.strip()
for atom in 'WM_NAME', '_NET_WM_NAME':
    subprocess.run(['xprop',
                    '-format', '_NET_WM_NAME', '8s',
                    '-id', net_active_window,
                    '-set', atom, title],
                   check=True,
                   stdin=subprocess.DEVNULL,
                   stdout=subprocess.DEVNULL,
                   stderr=subprocess.PIPE)
