#! /usr/bin/env python3

import subprocess
from json import loads
import sys

net_active_window = subprocess.run(['xprop',
                                    '-root',
                                    '32x', '\\t$0',
                                    '_NET_ACTIVE_WINDOW'],
                                   check=True,
                                   stdin=subprocess.DEVNULL,
                                   stdout=subprocess.PIPE,
                                   stderr=subprocess.PIPE,
                                   universal_newlines=True) \
                              .stdout \
                              .rsplit('\t', maxsplit=1)[-1]

title = subprocess.run(["dmenu"] + sys.argv[1:],
                       check=True,
                       stdin=subprocess.DEVNULL,
                       stdout=subprocess.PIPE,
                       stderr=subprocess.PIPE,
                       universal_newlines=True).stdout.strip()
subprocess.run(['xprop',
                '-format', '_NET_WM_NAME', '8s',
                '-id', net_active_window,
                '-set', '_NET_WM_NAME', title],
               check=True,
               stdin=subprocess.DEVNULL,
               stdout=subprocess.DEVNULL,
               stderr=subprocess.PIPE)
