#! /usr/bin/env python3

from argparse import ArgumentParser, REMAINDER
import subprocess


argument_parser = ArgumentParser(description=__doc__)
argument_parser.add_argument('wmctrl_flag',
                             help='wmctrl flag to apply to window')
argument_parser.add_argument('dmenu_args', nargs=REMAINDER,
                             help='Command line arguments'
                                  ' to pass through to dmenu')

args = argument_parser.parse_args()

windows = {title.strip(): winid
           for line
           in subprocess.run(['wmctrl', '-l'],
                             check=True,
                             stdin=subprocess.DEVNULL,
                             stdout=subprocess.PIPE,
                             stderr=subprocess.PIPE,
                             universal_newlines=True)
                        .stdout
                        .splitlines()
           for winid, _desktop, _hostname, title
           in (line.split(maxsplit=3),)}
titles = subprocess.run(["dmenu"] + args.dmenu_args[1:],
                       check=True,
                       input='\n'.join(windows),
                       stdout=subprocess.PIPE,
                       stderr=subprocess.PIPE,
                       universal_newlines=True).stdout.splitlines()
for title in titles:
    subprocess.run(['wmctrl', '-i', args.wmctrl_flag, windows[title.strip()]],
                   check=True,
                   stdin=subprocess.DEVNULL,
                   stdout=subprocess.PIPE,
                   stderr=subprocess.PIPE,
                   universal_newlines=True)
